### ISSUE TITLE
Clean Code가 아닌 이슈 발생

### ISSUE THREAD

**Issue by MinseokGo** [seohyun09/REACT#1]
CSS, 설렘, 떠오름, 이서현 lets go!

# Issues
- [x] 제 1법칙, 백엔드를 절대 믿지 마라
- [x] 제 2법칙, 1법칙을 절대 준수하라
- [ ] 제 3법칙, 겠냐?

# Tasks
- [ ] 새도 매일 출석하기
- [ ] 새도 잔디 스트릭 대결하기
- [ ] 새도 잔류 시간 대결하기
- [ ] 갓생 살기
